config/routes.rb
Rails.application.routes.draw do

   scope "(:locale)", locale: /en|es/ do
  

  get 'pages/inicio'

  get 'pages/servicios'

  get 'pages/regiones'

  get 'pages/eventos'

  get 'pages/contactenos'

  match 'pages#inicio',  :anchor => '#contactenos',   to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]

  root 'pages#inicio'

  end

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :lastName,      :validate => true
  attribute :company,      :validate => true
  attribute :jobtitle,      :validate => true
  attribute :phone,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Cliente Potencial GlobalEventsDMC.com",
      :to => "contactus@globaleventsdmc.com",
      :from => %("#{name}" <#{email}>)
        

    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_locale
 
def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def inicio
    
  end

  def servicios
  end

  def regiones
  end

  def eventos
  end

  def contactenos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/_form.html.erb
<div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h3><%= t('contact_us_h1') %></h3>
                    <%= image_tag("hr_line.png", class: "line") %><br>
                    <h8><%= t('contact_us_h2') %></h8>
                </div>
                <div class="row">
  <div class="col-xs-4" style="padding-top: 20px;">
<%= image_tag("pin.svg", width: '20px', :style => "margin-left:20%;") %><p style="text-align: left; margin-left: 30%;">Boulevard Rohrmosser, <br>
Pavas, San José, <br>
Costa Rica</p>

<%= image_tag("mail.svg", width: '20px', :style => "margin-left:20%;") %><p style="text-align: left; margin-left: 30%;">contactus@globaleventsdmc.com</p>
<%= image_tag("phone.svg", width: '20px', :style => "margin-left:20%;") %><p style="text-align: left; margin-left: 30%;"><%= t('phone') %>: + (506) 2290-0731</p>

  </div>
  <div class="col-xs-8">
    <%= simple_form_for(Contact.new , :html => {:class => 'form-inline' }) do |f| %>
     <div class="col-xs-3  col-xs-offset-1">
      <div class="form-group">
    <%= f.input :name, :required => true %>
    </div>
    <div class="form-group">
    <%= f.input :lastName, :required => true %>
    </div>
    <div class="form-group">
    <%= f.input :company, :required => true %>
</div>
</div>
    <div class="col-xs-3  col-xs-offset-1">
    <div class="form-group">
    <%= f.input :jobtitle, :required => true %>
    </div>
    <div class="form-group">
    <%= f.input :phone, :required => true %>
    </div>
    <div class="form-group">
    <%= f.input :email, :required => true %>
    </div>
    </div>
</div>
     <div class="form-group col-xs-7 pull-right" style="margin-right:15px;">
    <div class="form-group">
    <%= f.input :message, :as => :text, :required => true, style: 'width:250px'%>
    </div>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>

    </div>
    <%= f.button :submit, t('send'), :class=> "btn btn-primary",  style: 'margin-top:18px;' %>
    </div>
<div> 
    </div><br>

<% end %>
</div>
</div>
            </div>
        </div>
        

app/views/contacts/_head.html.erb
 <!-- Navigation -->
     <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-non-responsive">
                     <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
</div>
            <!-- Collect the nav links, forms, and other content for toggling -->
                <ul class="nav navbar-nav">
                  <a style="margin-right: 10px;"><%= link_to image_tag("in.svg", :alt => "Brand", :width => 30), "https://www.linkedin.com/company/global-events-dmc", :target => "_blank" %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("fb.svg", :alt => "Brand", :width => 30), "https://www.facebook.com/pages/Global-Events-DMC/764542110267778", :target => "_blank" %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("Spain.png", :alt => "Brand", :width => 30), root_path(locale: 'es') %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("United-States.png", :alt => "Brand", :width => 30), root_path(locale: 'en') %></a>
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to t('home'), root_path, :class =>"page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('about_us'), root_path(:anchor => "nosotros"), :class =>"page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('testimonials'), root_path(:anchor => "servicios"), :class =>"page-scroll" %>
                    </li>
                    <li>
                 <a><%= image_tag("logo.svg", :alt => "Brand", :width => 120) %></a>        
                    </li>
                    <li>
                        <%= link_to t('services'), root_path(:anchor => "regiones"), :class =>"page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('regions'), root_path(:anchor => "eventos"), :class =>"page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('contact_us'), root_path(:anchor => "contactenos"), :class =>"page-scroll" %>
                    </li>
                </ul>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-non-responsive -->
    </nav>

app/views/contacts/create.html.erb
<%= render 'head' %>
<section id="nosotros" class="thanks-section">
        <div class="container">
            <h1><%=t('thanks')%></h1>
        </div>
    </section>

  

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Global Events DMC | Event company in Costa Rica, leaders in incentive travel, conventions and meetings in Costa Rica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//blueimp.github.io/Gallery/css/blueimp-gallery.min.css">
<link rel="stylesheet" href="css/bootstrap-image-gallery.min.css">
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:600,400' rel='stylesheet' type='text/css'>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <meta name="robots" content="index, follow" />
  <meta name="keywords" content="event management, event company" />
  <meta name="description" content="Global Events DMC | Event company in Costa Rica, leaders in incentive travel, conventions and meetings in Costa Rica. 25 years experience in event management, we cover Central America, Mexico and Dominican Republic" />
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

<%= yield %>

     <!-- Contactenos Section -->
    <section id="contactenos" class="contactenos-section">
        <%= render 'contacts/form', contact: @contact%>
    </section>


    <section>
        <div class="overlay" onClick="style.pointerEvents='none'"></div>
<iframe
  width="100%"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBASvPxI7KyxyLBM9xQqCdviLlYr9Ep-_g
    &q=9.953818, -84.125569">
</iframe>

</section>
<section class="footer-section">
  
<div>
  <a><%= image_tag("logo.svg", :alt => "Brand", :width => 120) %></a><div>

</section>
</body>
</html>

app/views/pages/contactenos.html.erb
<h1>Pages#contactenos</h1>
<p>Find me in app/views/pages/contactenos.html.erb</p>

app/views/pages/eventos.html.erb
<h1>Pages#eventos</h1>
<p>Find me in app/views/pages/eventos.html.erb</p>

app/views/pages/inicio.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-non-responsive">
                     <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
</div>
            <!-- Collect the nav links, forms, and other content for toggling -->
                <ul class="nav navbar-nav">
                  <a style="margin-right: 10px;"><%= link_to image_tag("in.svg", :alt => "Brand", :width => 30), "https://www.linkedin.com/company/global-events-dmc", :target => "_blank" %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("fb.svg", :alt => "Brand", :width => 30), "https://www.facebook.com/pages/Global-Events-DMC/764542110267778", :target => "_blank" %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("Spain.png", :alt => "Brand", :width => 30), root_path(locale: 'es'), data: { no_turbolink: true } %></a>
<a style="margin-left: 10px;"><%= link_to image_tag("United-States.png", :alt => "Brand", :width => 30), root_path(locale: 'en'), data: { no_turbolink: true } %></a>

                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <%= link_to t('home'), root_path, :class => "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('about_us'), root_path(:anchor => "nosotros"), :class => "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('testimonials'), root_path(:anchor => "servicios"), :class => "page-scroll" %>
                    </li>
                    <li>
                 <a><%= image_tag("logo.svg", :alt => "Brand", :width => 120) %></a>        
                    </li>
                    <li>
                        <%= link_to t('regions'), root_path(:anchor => "regiones"), :class => "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('services'), root_path(:anchor => "eventos"), :class => "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to t('contact_us'), root_path(:anchor => "contactenos"), :class => "page-scroll" %>
                    </li>
                </ul>
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Section -->
    <section id="intro" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
<ol class="carousel-indicators">
 <li data-target="#intro" data-slide-to="0" class="active"></li>
 <li data-target="#intro" data-slide-to="1"></li>
 <li data-target="#intro" data-slide-to="2"></li>
</ol>
<!-- Wrapper for slides -->
<div class="carousel-inner">
 <div class="item active">
 <%= image_tag("bg.jpg") %>
 <div class="carousel-caption">
                    <h1>Costa Rica</h1>
                    <%= image_tag("hr.png") %>
                    <h2><%= t('slide_1') %><br> <%= t('slide_1_br') %></h2>
 </div>
 </div>
 <div class="item">
 <%= image_tag("bg2.jpg") %>
 <div class="carousel-caption">
  <h1>Costa Rica</h1>
                    <%= image_tag("hr.png") %>
                    <h2><%= t('slide_2') %><br> <%= t('slide_2_br') %></h2>
 </div>
 </div>
 <div class="item">
 <%= image_tag("bg3.jpg") %>
 <div class="carousel-caption">
  <h1>Costa Rica</h1>
                    <%= image_tag("hr.png") %>
                    <h2><%= t('slide_3') %><br> <%= t('slide_3_br') %></h2>
 </div>
 </div>
</div>
<!-- Controls -->
<a class="left carousel-control" href="#intro" role="button" data-slide="prev">
 <span class="glyphicon glyphicon-chevron-left"></span>
</a>
<a class="right carousel-control" href="#intro" role="button" data-slide="next">
 <span class="glyphicon glyphicon-chevron-right"></span>
</a>
</div>

    </section>

    <!-- Nosotros Section -->
    <section id="nosotros" class="nosotros-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h3><%= t('about_us_h3') %> </h3>
                    <%= image_tag("hr_line.png", class: "line") %>
                </div>
                <div class="row">
  <div class="col-xs-3">
    <div>
      <div class="caption">
        <h4><%= t('about_us_caption1') %><br>
<%= t('about_us_caption2') %><br>
<%= t('about_us_caption3') %></h4><br><br><br>
        <p><a href="#servicios" class="btn btn-danger" role="button"><%= t('read_more') %></a></p><br>
      </div>
    </div>
  </div>
  <div >
   <p style="font-size: 15px; text-align: justify"><%= t('about_us_p1') %><br><br><%= t('about_us_p2') %>
</p> 
</div>
            </div>
        </div>
        <p style="text-align: right; margin-top: 30px; font-size: 16px;"><%= image_tag("mail.svg", width: '20px') %> <b>contactus@globaleventsdmc.com <b><%= image_tag("phone.svg", width: '20px') %><b><%=t('phone')%>: + (506) 2291-8173<b></p>
    </section>

    <!-- Servicios Section -->
    <section id="servicios" class="servicios-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1><%= t('servicios_h1') %></h1>
                    <hr></hr>
                    <h5><%= t('servicios_h5') %></h5><br><br>
                    <div id="testimonios" class="carousel slide" data-ride="carousel">
                      <ol class="carousel-indicators" style="bottom: -30px;">
 <li data-target="#testimonios" data-slide-to="0" class="active"></li>
 <li data-target="#testimonios" data-slide-to="1"></li>
</ol>
<div class="carousel-inner">
 <div class="item active">
  <blockquote>"<%= t('servicios_quote1') %>"
<cite><%= t('servicios_cite1') %></cite></blockquote> 
 </div>
 <div class="item">
  <blockquote>"<%= t('servicios_quote2') %>"
<cite><%= t('servicios_cite2') %></cite></blockquote> 
 </div>
</div>
                </div>
            </div>

        </div>
        <p style="text-align: right; margin-top: 30px; font-size: 16px;"><%= image_tag("mail.svg", width: '20px') %> <b>contactus@globaleventsdmc.com <b><%= image_tag("phone.svg", width: '20px') %><b><%=t('phone')%>: + (506) 2291-8173<b></p>
    </section>
    <!-- Regiones Section -->
    <section id="regiones" class="regiones-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                   <h7><%= t('regiones_h7') %></h7><br>
                    <%= image_tag("hr_line.png", class: "line") %><br>
                    <h8 style="text-align: justify;"><%= t('regiones_p1') %></h8>
                </div>
                <div class="row">
  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("norte.jpg", width: '370') %>
      <div class="caption">
        <h3><%= t('norte_h1') %></h3>
        <p style="text-align: justify;"><%= t('norte_p1') %></p>
        <p><%= link_to t('read_more'), pages_regiones_path(:anchor => "norte"), :class => "btn btn-danger", :role => "button" %></p>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("webjpg-43.jpg", width: '370') %>
      <div class="caption">
        <h3><%= t('central_h1') %></h3>
        <p style="text-align: justify;"><%= t('central_p1') %>
</p>
        <p><%= link_to t('read_more'), pages_regiones_path(:anchor => "central"), :class => "btn btn-danger", :role => "button" %></p>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag("central.jpg", width: '370') %>
      <div class="caption">
        <h3><%= t('valley_h1') %></h3>
        <p style="text-align: justify;"><%= t('valley_p1') %>
</p>
        <p><%= link_to t('read_more'), pages_regiones_path(:anchor => "valle"), :class => "btn btn-danger", :role => "button" %></p>
      </div>
    </div>
  </div>
</div>
            </div>
             <p style="text-align: right; margin-top: 30px; font-size: 16px;"><%= image_tag("mail.svg", width: '20px') %> <b>contactus@globaleventsdmc.com <b><%= image_tag("phone.svg", width: '20px') %><b><%=t('phone')%>: + (506) 2291-8173<b></p>
        </div>
        
    </section>
     <!-- Eventos Section -->
    <section id="eventos" class="eventos-section">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                   <h1><%= t('services_h1') %></h1>
                </div>
                <div class="row">
  <div class="col-xs-3">
    <div>
      <div class="caption">
         <h3><%= t('services_p1') %></h3>
                    <%= image_tag("hr_line.png", class: "line") %>

                    <h5 style="text-align: left; align: justify;"><%= t('services_p2') %><br><br>
<strong><%= t('services_p3') %></strong><br>
<%= t('services_p4') %><br>

<%= t('services_p5') %><br>

<%= t('services_p6') %><br>

<%= t('services_p7') %><br>

<%= t('services_p8') %><br>

<%= t('services_p9') %><br>

<%= t('services_p10') %><br>

<%= t('services_p11') %><br>

<%= t('services_p12') %><br>

<%= t('services_p13') %></h5>
       
      </div>
    </div>
  </div>
  <div >
    <div class="row" style="margin-top: 100px;">
            <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event1.jpg", width: '200') %>
                </a>
            </div>
            <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event2.jpg", width: '200') %>
                </a>
            </div>
            <div class="col-xs-2 portfolio-item">
                <a>
                   <%= image_tag("event3.jpg", width: '200') %>
                </a>
            </div>
            <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event4.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                   <%= image_tag("event5.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event6.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event7.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event8.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event9.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event10.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event11.jpg", width: '200') %>
                </a>
            </div>
             <div class="col-xs-2 portfolio-item">
                <a>
                    <%= image_tag("event12.jpg", width: '200') %>
                </a>
            </div>
             <%= link_to t('gallery_1'), pages_servicios_path, :class => "btn btn-default", :role => "button", :style => "margin-top:20px;" %>
</div>
            </div>
        </div> 
              
            


        </div>
          <p style="text-align: right; margin-top: 30px; font-size: 16px;"><%= image_tag("mail.svg", width: '20px') %> <b>contactus@globaleventsdmc.com <b><%= image_tag("phone.svg", width: '20px') %><b><%=t('phone')%>: + (506) 2291-8173<b></p>
            </div>

        </div>
        
    </section>
 <!-- Scrolling Nav JavaScript -->
    <script src="javascripts/application.js"></script>
<script>
$(document).ready(function(){
$('.carousel').carousel({
interval: 10000
 });
});
</script>